// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZHZiF1oIfzsGsQTct7DgZErCP-3JmLCY',
    appId: '1:280843036910:web:2990b1c63537d13fb46bff',
    messagingSenderId: '280843036910',
    projectId: 'listadecompra-f8ffe',
    authDomain: 'listadecompra-f8ffe.firebaseapp.com',
    storageBucket: 'listadecompra-f8ffe.firebasestorage.app',
    measurementId: 'G-KKVEFLRZBS',
  );

  // Configuração para Web

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBA-Fy1NWY7IDhK2wSIXrATItSPteWoNA',
    appId: '1:280843036910:android:4ee888309293a0ebb46bff',
    messagingSenderId: '280843036910',
    projectId: 'listadecompra-f8ffe',
    storageBucket: 'listadecompra-f8ffe.firebasestorage.app',
  );

  // Configuração para Android

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfyt7bVp5Q78jxp5i2GYdEEZnocZtJ93A',
    appId: '1:280843036910:ios:b9666b41e66a3520b46bff',
    messagingSenderId: '280843036910',
    projectId: 'listadecompra-f8ffe',
    storageBucket: 'listadecompra-f8ffe.firebasestorage.app',
    iosBundleId: 'com.example.listadecompra',
  );

  // Configuração para iOS

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfyt7bVp5Q78jxp5i2GYdEEZnocZtJ93A',
    appId: '1:280843036910:ios:b9666b41e66a3520b46bff',
    messagingSenderId: '280843036910',
    projectId: 'listadecompra-f8ffe',
    storageBucket: 'listadecompra-f8ffe.firebasestorage.app',
    iosBundleId: 'com.example.listadecompra',
  );

  // Configuração para macOS

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZHZiF1oIfzsGsQTct7DgZErCP-3JmLCY',
    appId: '1:280843036910:web:44d77402ec2bff8ab46bff',
    messagingSenderId: '280843036910',
    projectId: 'listadecompra-f8ffe',
    authDomain: 'listadecompra-f8ffe.firebaseapp.com',
    storageBucket: 'listadecompra-f8ffe.firebasestorage.app',
    measurementId: 'G-5SSNV58Z8E',
  );

  // Configuração para Windows
}